# Generated by Django 4.2.7 on 2023-11-13 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('data_criada', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
