# Generated by Django 4.2.7 on 2023-11-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_categoria_clube_jogador_jogo_quadra_delete_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jogador',
            new_name='Jogadore',
        ),
    ]
