# Generated by Django 4.2.7 on 2023-11-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_jogador_jogadore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogadore',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
    ]
